'use client';
import { useEffect,useState } from 'react';
import { ArrowUpRight,ArrowRight,Plus,Search,Users,Target,MessageSquare,Phone,Mail,CalendarDays,Check,ChevronLeft,ChevronRight,Clock,FileText,Building2,CheckCheck,SlidersHorizontal,ArrowDown,ExternalLink,LayoutGrid,LoaderCircle,Info,Pencil,AlertCircle } from 'lucide-react';
import { Tabs,TabsList,TabsTrigger,TabsContent } from '@/components/ui/tabs';
import { Dialog,DialogContent,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { Sheet,SheetContent,SheetTitle,SheetDescription } from '@/components/ui/sheet';
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from '@/components/ui/select';
import { Progress } from '@/components/ui/progress';
import { Table,TableHeader,TableHead,TableBody,TableRow,TableCell } from '@/components/ui/table';
import { Toaster,toast } from 'sonner';
import { type Client,type Interaction,stages,money,dayLabel,isoDay,reasons } from '@/lib/crm';
const sections=[['priorities','Mes priorités'],['clients','Clients 360°'],['interactions','Interactions'],['opportunities','Opportunités & devis']];
function Pick({value,onChange,options,label}:{value:string,onChange:(s:string)=>void,options:{value:string,label:string}[],label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="pick"><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{options.map(x=><SelectItem key={x.value} value={x.value}>{x.label}</SelectItem>)}</SelectContent></Select>}
function Circle({children,onClick,label,className=''}:{children:React.ReactNode,onClick?:()=>void,label:string,className?:string}){return <button type="button" className={'circle '+className} onClick={onClick} aria-label={label} title={label}>{children}</button>}
export default function CRM(){
const [clients,setClients]=useState<Client[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[tab,setTab]=useState('priorities'),[query,setQuery]=useState(''),[filter,setFilter]=useState('Toutes'),[focusId,setFocusId]=useState('atelier'),[detailId,setDetailId]=useState<string|null>(null),[dialog,setDialog]=useState(false),[edit,setEdit]=useState<Client|null>(null),[saving,setSaving]=useState(false),[calendarOffset,setCalendarOffset]=useState(0),[calendarDay,setCalendarDay]=useState<string|null>(null);
const [form,setForm]=useState({clientId:'atelier',contact:'none',type:'Appel',result:'',next:'',due:isoDay(1)});
async function load(){setLoading(true);setError('');try{const r=await fetch('/api/clients');if(!r.ok)throw Error('Les fiches clients ne sont pas disponibles pour le moment.');setClients(await r.json())}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
useEffect(()=>{load()},[]);
const focus=clients.find(c=>c.id===focusId)||clients[0],detail=clients.find(c=>c.id===detailId),formClient=clients.find(c=>c.id===form.clientId);
const openClients=clients.filter(c=>!['Gagné','Perdu'].includes(c.opportunity.stage));
const dueClients=clients.filter(c=>c.due&&c.due<=isoDay());
const interactions=clients.flatMap(c=>c.interactions.map(i=>({...i,client:c}))).sort((a,b)=>b.date.localeCompare(a.date));
const filtered=clients.filter(c=>(c.name+' '+c.city+' '+c.contacts.map(x=>x.name).join(' ')).toLowerCase().includes(query.toLowerCase())).filter(c=>filter==='Toutes'||(filter==='À relancer'&&c.due<=isoDay())||(filter==='À qualifier'&&reasons(c).some(x=>/qualifier|inconnu/.test(x)))||(filter==='Contacts à vérifier'&&!c.contacts.some(x=>x.status==='Vérifié')));
async function save(c:Client){setSaving(true);try{const r=await fetch('/api/clients',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(c)});const out=await r.json() as Client & {error?:string};if(!r.ok)throw Error(out.error||'Enregistrement impossible.');setClients(old=>old.map(x=>x.id===out.id?out:x));return true}catch(e){toast.error((e as Error).message);return false}finally{setSaving(false)}}
function openInteraction(c=focus){if(!c)return;setForm({clientId:c.id,contact:c.contacts.find(x=>x.status==='Vérifié')?.id||'none',type:'Appel',result:'',next:c.next,due:c.due<isoDay()?isoDay():c.due});setDialog(true)}
async function submit(e:React.FormEvent){e.preventDefault();if(!formClient||!form.result.trim()||!form.next.trim())return;const contact=formClient.contacts.find(x=>x.id===form.contact&&x.status==='Vérifié');const item:Interaction={id:crypto.randomUUID(),date:new Date().toISOString(),type:form.type as Interaction['type'],contact:contact?.name||'Contact non confirmé',result:form.result.trim(),next:form.next.trim(),due:form.due};if(await save({...formClient,next:item.next,due:item.due,interactions:[item,...formClient.interactions]})){setDialog(false);toast.success('Échange enregistré. La mémoire client est à jour.')}}
const month=new Date();month.setDate(1);month.setMonth(month.getMonth()+calendarOffset);const monthStart=(month.getDay()+6)%7,monthDays=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();
const calendarDates=Array.from({length:monthStart+monthDays},(_,i)=>i<monthStart?null:`${month.getFullYear()}-${String(month.getMonth()+1).padStart(2,'0')}-${String(i-monthStart+1).padStart(2,'0')}`);
const contact=focus?.contacts.find(x=>x.status==='Vérifié');
return <><Toaster position="bottom-right" richColors/><Tabs value={tab} onValueChange={v=>{setTab(v);setQuery('');setFilter('Toutes')}} className="app-shell">
<header className="topbar"><a className="brand" href="/" aria-label="NOVELYS accueil"><img src="/novelys-mark.png" alt=""/><span>NOVELYS<small>mémoire client</small></span></a><TabsList className="main-nav">{sections.map(([v,l])=><TabsTrigger value={v} key={v}>{l}</TabsTrigger>)}</TabsList><div className="workspace"><span className="workspace-name">Espace FULL ACE</span><span className="avatar owner" title="Équipe commerciale">FA</span></div></header>
<main><div className="heading"><div><div className="eyebrow">VOTRE ESPACE COMMERCIAL <span>/</span> FULL ACE</div><h1>{sections.find(x=>x[0]===tab)?.[1]}</h1><p>{tab==='priorities'?'Les bons contacts. Le bon contexte. La prochaine action.':tab==='clients'?'Toute la connaissance client, au même endroit.':tab==='interactions'?'Chaque échange enrichit votre mémoire client.':'Des besoins identifiés aux projets concrétisés.'}</p></div><div className="heading-actions"><span className="today">{new Date().toLocaleDateString('fr-FR',{day:'numeric',month:'long',year:'numeric'})}</span><button className="primary" disabled={!clients.length} onClick={()=>openInteraction()}><Plus size={18}/>Nouvelle interaction</button></div></div>
{loading?<div className="loading"><LoaderCircle className="spin"/>Chargement de votre espace…</div>:error?<div className="empty"><AlertCircle/><p>{error}</p><button className="primary" onClick={load}>Réessayer</button></div>:<>
<div className="metrics"><div className="metric"><span className="metric-icon"><Target/></span><div><strong>{dueClients.length.toString().padStart(2,'0')}<span className="metric-pill">à traiter</span></strong><p>Actions à échéance</p></div></div><div className="metric"><span className="metric-icon"><Users/></span><div><strong>{clients.length.toString().padStart(2,'0')}<span className="metric-note">comptes suivis</span></strong><p>Votre portefeuille client</p></div></div><div className="metric"><span className="metric-icon"><ArrowUpRight/></span><div><strong>{money(openClients.reduce((s,c)=>s+c.opportunity.amount,0))}<span className="metric-note">{openClients.length} opportunités</span></strong><p>Montant des projets en cours</p></div></div><div className="demo-label"><span className="demo-dot"/>Données de démonstration<small>Scénarios fictifs · MVP</small></div></div>
<TabsContent value="priorities"><div className="dashboard-grid"><div className="main-column"><section className="panel priorities-panel"><div className="panel-title"><div><h2>À vous de jouer <span className="count">{filtered.length}</span></h2><p>Chaque priorité a une raison.</p></div><Pick value={filter} onChange={setFilter} label="Filtrer les priorités" options={['Toutes','À relancer','À qualifier','Contacts à vérifier'].map(v=>({value:v,label:v==='Toutes'?'Toutes les priorités':v}))}/></div><div className="priority-grid">{filtered.map(c=><button key={c.id} className={'priority-card '+c.color+(focusId===c.id?' selected':'')} onClick={()=>setFocusId(c.id)} aria-pressed={focusId===c.id}><div className="card-top"><span className="company-mark">{c.initials}</span><ArrowUpRight size={19}/></div><span className="priority-reason">{reasons(c)[0]||'Suivi de la relation'}</span><h3>{c.name}</h3><p>{c.next}</p><div className="card-bottom"><span><Clock size={13}/>{c.due<isoDay()?'En retard':c.due===isoDay()?"Aujourd’hui":dayLabel(c.due)}</span><span>{money(c.opportunity.amount)}</span></div></button>)}</div>{!filtered.length&&<div className="empty">Aucune priorité dans cette catégorie.</div>}</section>
<div className="lower-grid"><section className="panel calendar-panel"><div className="panel-title"><h2>Votre agenda</h2><CalendarDays size={18}/></div><div className="month-nav"><Circle label="Mois précédent" onClick={()=>{setCalendarOffset(x=>x-1);setCalendarDay(null)}}><ChevronLeft/></Circle><strong>{month.toLocaleDateString('fr-FR',{month:'long',year:'numeric'})}</strong><Circle label="Mois suivant" onClick={()=>{setCalendarOffset(x=>x+1);setCalendarDay(null)}}><ChevronRight/></Circle></div><div className="calendar-grid">{['L','M','M','J','V','S','D'].map((d,i)=><span className="weekday" key={i}>{d}</span>)}{calendarDates.map((d,i)=>d?<button key={d} aria-label={dayLabel(d)} onClick={()=>setCalendarDay(d)} className={(d===isoDay()?'current-day ':'')+(d===calendarDay?'picked ':'')+(clients.some(c=>c.due===d)?'has-event':'')}>{Number(d.slice(-2))}{clients.some(c=>c.due===d)&&<i/>}</button>:<span key={'empty'+i}/>)}</div><div className="calendar-caption">{calendarDay?(clients.filter(c=>c.due===calendarDay).map(c=><button key={c.id} onClick={()=>setDetailId(c.id)}>{c.name}<ArrowUpRight size={14}/></button>)): <><span className="legend-dot"/>Prochaines actions planifiées</>}{calendarDay&&!clients.some(c=>c.due===calendarDay)&&'Aucune action prévue ce jour.'}</div></section>
<section className="panel pipeline-panel"><div className="panel-title"><h2>Vos opportunités</h2><Circle label="Voir toutes les opportunités" onClick={()=>setTab('opportunities')}><ArrowUpRight/></Circle></div><div className="pipeline-total">{money(openClients.reduce((s,c)=>s+c.opportunity.amount,0))}<p>dans votre pipeline</p></div><div className="funnel">{stages.slice(0,3).map((s,i)=>{const cs=clients.filter(c=>c.opportunity.stage===s);return <button key={s} style={{width:`${100-i*12}%`}} onClick={()=>setTab('opportunities')}><span>{s}<small>{cs.length} projet{cs.length>1?'s':''}</small></span><strong>{money(cs.reduce((sum,c)=>sum+c.opportunity.amount,0))}</strong></button>})}</div><div className="won"><CheckCheck size={16}/>{money(clients.filter(c=>c.opportunity.stage==='Gagné').reduce((s,c)=>s+c.opportunity.amount,0))} de projets gagnés</div></section></div></div>
<aside className="right-column">{focus&&<><section className="focus-card"><div className="focus-top"><span>CLIENT À LA UNE</span><Circle label={'Ouvrir '+focus.name} onClick={()=>setDetailId(focus.id)}><ArrowUpRight/></Circle></div><div className="focus-monogram">{focus.initials}</div><h2>{focus.name}</h2><p>{focus.sector} <span>·</span> {focus.city}</p><div className="focus-contact"><span className="avatar">{contact?contact.name.split(' ').map(x=>x[0]).join(''):'?'}</span><div><strong>{contact?.name||'Contact à confirmer'}</strong><span>{contact?.role||'Aucun contact vérifié'}</span></div>{contact&&<Check size={16}/>}</div><button className="focus-open" onClick={()=>setDetailId(focus.id)}>Ouvrir la fiche 360°<ArrowRight size={17}/></button></section><section className="panel context-panel"><div className="panel-title"><h2>Le contexte, en bref</h2><span className="context-icon"><FileText size={16}/></span></div><p className="context-summary">{focus.summary}</p><div className="key-facts"><div><span>Dernière commande</span><strong>{dayLabel(focus.lastOrder)}</strong></div><div><span>Historique client</span><strong>{focus.orders} commandes</strong></div><div><span>Famille de produits</span><strong>{focus.family}</strong></div></div><div className="next-action"><span className="eyebrow">PROCHAINE ACTION</span><p>{focus.next}</p><span className="action-date"><CalendarDays size={14}/>{dayLabel(focus.due)}</span><button onClick={()=>openInteraction(focus)}>Enregistrer un échange<Plus size={16}/></button></div></section></>}</aside></div></TabsContent>
<TabsContent value="clients"><section className="panel directory"><div className="panel-title"><h2>Votre portefeuille <span className="count">{filtered.length}</span></h2><label className="search"><Search size={18}/><input aria-label="Rechercher un client" placeholder="Rechercher un client, un contact…" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><Table><TableHeader><TableRow><TableHead>Entreprise</TableHead><TableHead>Contact recommandé</TableHead><TableHead>À suivre</TableHead><TableHead>Commandes</TableHead><TableHead>Prochaine action</TableHead><TableHead><span className="sr-only">Ouvrir</span></TableHead></TableRow></TableHeader><TableBody>{filtered.map(c=>{const p=c.contacts.find(x=>x.status==='Vérifié');return <TableRow key={c.id}><TableCell><button className="company-cell" onClick={()=>setDetailId(c.id)}><span className={'company-mark '+c.color}>{c.initials}</span><span><strong>{c.name}</strong><small>{c.city} · {c.sector}</small></span></button></TableCell><TableCell>{p?<><strong>{p.name}</strong><small>{p.role}</small></>:<span className="status warning">À vérifier</span>}</TableCell><TableCell><span className="status">{reasons(c)[0]||'Relation à entretenir'}</span></TableCell><TableCell>{c.orders}<small>{money(c.revenue)}</small></TableCell><TableCell>{dayLabel(c.due)}<small>{c.next}</small></TableCell><TableCell><Circle label={'Voir '+c.name} onClick={()=>setDetailId(c.id)}><ArrowUpRight/></Circle></TableCell></TableRow>})}</TableBody></Table>{!filtered.length&&<div className="empty">Aucun client trouvé. Essayez un autre nom.</div>}</section></TabsContent>
<TabsContent value="interactions"><section className="panel interactions-panel"><div className="panel-title"><h2>La mémoire des échanges <span className="count">{interactions.length}</span></h2><label className="search"><Search size={18}/><input aria-label="Rechercher un échange" placeholder="Rechercher dans les échanges…" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="timeline">{interactions.filter(i=>(i.result+i.client.name+i.contact).toLowerCase().includes(query.toLowerCase())).map(i=><article className="timeline-item" key={i.id}><span className="timeline-icon">{i.type==='Appel'?<Phone size={18}/>:i.type==='E-mail'?<Mail size={18}/>:<MessageSquare size={18}/>}</span><div><div className="interaction-heading"><button onClick={()=>setDetailId(i.client.id)}>{i.client.name}<ArrowUpRight size={15}/></button><span>{new Date(i.date).toLocaleDateString('fr-FR')} · {i.type}</span></div><p className="contact-name">{i.contact}</p><p>{i.result}</p><div className="interaction-next"><ArrowRight size={15}/>{i.next}<span>{dayLabel(i.due)}</span></div></div></article>)}</div>{!interactions.some(i=>(i.result+i.client.name+i.contact).toLowerCase().includes(query.toLowerCase()))&&<div className="empty">Aucun échange trouvé.</div>}</section></TabsContent>
<TabsContent value="opportunities"><div className="board-heading"><p>{clients.length} projets suivis <span>·</span> Montants non pondérés</p></div><div className="kanban">{stages.map((s,index)=><section className="kanban-column" key={s}><h2><i style={{background:['#a6afd2','#789cf7','#1947d1','#38765f','#8c8f9b'][index]}}/>{s}<span>{clients.filter(c=>c.opportunity.stage===s).length}</span></h2><p className="column-total">{money(clients.filter(c=>c.opportunity.stage===s).reduce((sum,c)=>sum+c.opportunity.amount,0))}</p>{clients.filter(c=>c.opportunity.stage===s).map(c=><article className="deal" key={c.id}><button className="deal-company" onClick={()=>setDetailId(c.id)}><span className={'company-mark '+c.color}>{c.initials}</span><ArrowUpRight size={17}/></button><h3>{c.name}</h3><p>{c.opportunity.name}</p><strong className="deal-amount">{money(c.opportunity.amount)}</strong><div className="deal-detail"><CalendarDays size={14}/>{c.opportunity.deadline?dayLabel(c.opportunity.deadline):'Calendrier à qualifier'}</div><Pick label={'Statut '+c.name} value={s} options={stages.map(x=>({value:x,label:x}))} onChange={async v=>{if(saving)return;if(await save({...c,opportunity:{...c.opportunity,stage:v as Client['opportunity']['stage']}}))toast.success('Statut du projet mis à jour.')}}/></article>)}{!clients.some(c=>c.opportunity.stage===s)&&<div className="board-empty">Aucun projet à cette étape</div>}</section>)}</div></TabsContent>
</>}
<footer><span><img src="/novelys-mark.png" alt=""/>Une relation se construit. Sa mémoire aussi.</span><span>NOVELYS <span className="footer-sep">/</span> Prototype FULL ACE</span></footer></main></Tabs>
<Sheet open={!!detailId} onOpenChange={v=>!v&&setDetailId(null)}><SheetContent className="client-sheet">{detail&&<><div className="sheet-top"><span className={'company-mark '+detail.color}>{detail.initials}</span><div><SheetTitle>{detail.name}</SheetTitle><SheetDescription>{detail.sector} · {detail.city}</SheetDescription></div></div><div className="sheet-actions"><button className="primary" onClick={()=>openInteraction(detail)}><Plus size={17}/>Enregistrer un échange</button><button className="secondary" onClick={()=>setEdit(structuredClone(detail))}><Pencil size={16}/>Qualifier</button></div><Tabs defaultValue="context" className="detail-tabs"><TabsList><TabsTrigger value="context">Contexte</TabsTrigger><TabsTrigger value="contacts">Contacts</TabsTrigger><TabsTrigger value="history">Historique</TabsTrigger></TabsList><TabsContent value="context"><section className="sheet-section"><h3>Ce que l’on sait</h3><p>{detail.summary}</p><div className="detail-stats"><div><strong>{detail.orders}</strong><span>commandes</span></div><div><strong>{money(detail.revenue)}</strong><span>CA historique simulé</span></div></div></section><section className="sheet-section"><h3>Opportunité en cours</h3><p>{detail.opportunity.name}</p><dl><div><dt>Montant</dt><dd>{money(detail.opportunity.amount)}</dd></div><div><dt>Statut du devis</dt><dd>{detail.opportunity.stage==='À qualifier'?'Non renseigné':detail.opportunity.stage}</dd></div><div><dt>Décideur</dt><dd>{detail.opportunity.decisionMaker||'À qualifier'}</dd></div><div><dt>Calendrier</dt><dd>{dayLabel(detail.opportunity.deadline)}</dd></div><div><dt>Logo exploitable</dt><dd>{detail.opportunity.logo?'Disponible':'Manquant'}</dd></div></dl></section><div className="next-action"><span className="eyebrow">PROCHAINE ACTION · {dayLabel(detail.due)}</span><p>{detail.next}</p></div></TabsContent><TabsContent value="contacts"><p className="contact-help">Seuls les contacts vérifiés sont proposés pour les échanges. Les contacts partis restent dans l’historique.</p>{detail.contacts.map(c=><article className={'contact-card '+(c.status==='Parti'?'departed':'')} key={c.id}><span className="avatar">{c.name.split(' ').map(n=>n[0]).join('')}</span><div><h3>{c.name}</h3><p>{c.role||'Rôle à qualifier'}</p><p>{c.email||'E-mail non renseigné'}</p><span className={'status '+(c.status==='Vérifié'?'verified':'warning')}>{c.status}</span>{c.verified&&<small>Vérifié le {dayLabel(c.verified)}</small>}</div></article>)}<button className="secondary" onClick={()=>setEdit(structuredClone(detail))}><Pencil size={16}/>Mettre à jour les contacts</button></TabsContent><TabsContent value="history">{detail.interactions.map(i=><article className="history-card" key={i.id}><span>{new Date(i.date).toLocaleDateString('fr-FR')} · {i.type}</span><h3>{i.contact}</h3><p>{i.result}</p><div><ArrowRight size={15}/>{i.next} · {dayLabel(i.due)}</div></article>)}</TabsContent></Tabs></>}</SheetContent></Sheet>
<Dialog open={dialog} onOpenChange={setDialog}><DialogContent className="form-dialog"><DialogTitle>Enregistrer un échange</DialogTitle><DialogDescription>Conservez ce que vous avez appris et la prochaine étape.</DialogDescription><form onSubmit={submit}><label>Client<Pick value={form.clientId} onChange={id=>{const c=clients.find(x=>x.id===id)!;setForm({...form,clientId:id,contact:c.contacts.find(x=>x.status==='Vérifié')?.id||'none',next:c.next})}} label="Client" options={clients.map(c=>({value:c.id,label:c.name}))}/></label><div className="form-row"><label>Type d’échange<Pick value={form.type} onChange={v=>setForm({...form,type:v})} label="Type d’échange" options={['Appel','E-mail','Rendez-vous','Note'].map(x=>({value:x,label:x}))}/></label><label>Interlocuteur<Pick value={form.contact} onChange={v=>setForm({...form,contact:v})} label="Interlocuteur" options={[{value:'none',label:'Contact non confirmé'},...(formClient?.contacts.filter(x=>x.status==='Vérifié').map(c=>({value:c.id,label:c.name}))||[])]}/></label></div><label htmlFor="result">Ce que vous avez appris<textarea id="result" required maxLength={3000} rows={4} placeholder="Besoin exprimé, décision, informations à retenir…" value={form.result} onChange={e=>setForm({...form,result:e.target.value})}/></label><label htmlFor="next">Prochaine action<input id="next" required maxLength={300} value={form.next} onChange={e=>setForm({...form,next:e.target.value})}/></label><label htmlFor="due">Date de la prochaine action<input id="due" type="date" required value={form.due} onChange={e=>setForm({...form,due:e.target.value})}/></label><div className="form-footer"><button type="button" className="secondary" onClick={()=>setDialog(false)}>Annuler</button><button className="primary" disabled={saving}>{saving?<LoaderCircle className="spin" size={16}/>:<Check size={16}/>}Enregistrer l’échange</button></div></form></DialogContent></Dialog>
<Dialog open={!!edit} onOpenChange={v=>!v&&setEdit(null)}><DialogContent className="form-dialog qualification"><DialogTitle>Qualifier la fiche client</DialogTitle><DialogDescription>{edit?.name} · Une information inconnue peut rester vide.</DialogDescription>{edit&&<form onSubmit={async e=>{e.preventDefault();if(await save(edit)){setEdit(null);toast.success('Fiche client mise à jour.')}}}><label>Contexte du compte<textarea rows={3} value={edit.summary} onChange={e=>setEdit({...edit,summary:e.target.value})}/></label><div className="form-row"><label>Décideur<input value={edit.opportunity.decisionMaker} placeholder="À qualifier" onChange={e=>setEdit({...edit,opportunity:{...edit.opportunity,decisionMaker:e.target.value}})}/></label><label>Échéance du projet<input type="date" value={edit.opportunity.deadline} onChange={e=>setEdit({...edit,opportunity:{...edit.opportunity,deadline:e.target.value}})}/></label></div><div className="form-row"><label>Statut du devis<Pick label="Statut du devis" value={edit.opportunity.stage} options={stages.map(x=>({value:x,label:x}))} onChange={v=>setEdit({...edit,opportunity:{...edit.opportunity,stage:v as Client['opportunity']['stage']}})}/></label><label>Logo exploitable<Pick label="Logo exploitable" value={edit.opportunity.logo?'yes':'no'} options={[{value:'yes',label:'Disponible'},{value:'no',label:'Manquant'}]} onChange={v=>setEdit({...edit,opportunity:{...edit.opportunity,logo:v==='yes'}})}/></label></div><h3>Contacts</h3>{edit.contacts.map((c,i)=><div className="contact-edit" key={c.id}><label>Nom<input required value={c.name} onChange={e=>setEdit({...edit,contacts:edit.contacts.map((x,j)=>j===i?{...x,name:e.target.value}:x)})}/></label><label>Rôle<input value={c.role} onChange={e=>setEdit({...edit,contacts:edit.contacts.map((x,j)=>j===i?{...x,role:e.target.value}:x)})}/></label><label>E-mail<input type="email" value={c.email} onChange={e=>setEdit({...edit,contacts:edit.contacts.map((x,j)=>j===i?{...x,email:e.target.value}:x)})}/></label><label>Fiabilité<Pick label={'Fiabilité '+c.name} value={c.status} options={['Vérifié','À revérifier','Parti'].map(x=>({value:x,label:x}))} onChange={v=>setEdit({...edit,contacts:edit.contacts.map((x,j)=>j===i?{...x,status:v as typeof c.status,verified:v==='Vérifié'?isoDay():null}:x)})}/></label></div>)}<button type="button" className="text-button" onClick={()=>setEdit({...edit,contacts:[...edit.contacts,{id:crypto.randomUUID(),name:'',role:'',email:'',status:'À revérifier',verified:null}]})}><Plus size={16}/>Ajouter un contact ou un remplaçant</button><div className="form-footer"><button type="button" className="secondary" onClick={()=>setEdit(null)}>Annuler</button><button className="primary" disabled={saving}>{saving?'Enregistrement…':'Enregistrer la fiche'}</button></div></form>}</DialogContent></Dialog>
</>;
}
