import { z } from 'zod';
export const contactSchema=z.object({id:z.string(),name:z.string().min(1).max(100),role:z.string().max(100),email:z.string().max(160),status:z.enum(['Vérifié','À revérifier','Parti']),verified:z.string().nullable()});
export const interactionSchema=z.object({id:z.string(),date:z.string(),type:z.enum(['Appel','E-mail','Rendez-vous','Note']),contact:z.string(),result:z.string().min(1).max(3000),next:z.string().min(1).max(300),due:z.string().regex(/^\d{4}-\d{2}-\d{2}$/)});
export const stages=['À qualifier','Devis à préparer','Devis envoyé','Gagné','Perdu'] as const;
export const clientSchema=z.object({id:z.string(),name:z.string().min(1).max(100),city:z.string(),sector:z.string(),family:z.string(),initials:z.string(),color:z.string(),summary:z.string(),orders:z.number(),revenue:z.number(),lastOrder:z.string(),contacts:z.array(contactSchema),opportunity:z.object({name:z.string(),amount:z.number().nonnegative(),stage:z.enum(stages),decisionMaker:z.string(),deadline:z.string(),logo:z.boolean()}),interactions:z.array(interactionSchema),next:z.string(),due:z.string(),revision:z.number().int()});
export type Client=z.infer<typeof clientSchema>;
export type Interaction=z.infer<typeof interactionSchema>;
export function isoDay(offset=0){const d=new Date();d.setDate(d.getDate()+offset);return d.toISOString().slice(0,10)}
export const money=(n:number)=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);
export function dayLabel(d:string){return d?new Date(d+'T12:00:00').toLocaleDateString('fr-FR',{day:'numeric',month:'short'}):'À qualifier'}
export function reasons(c:Client){const a:string[]=[];if(!c.contacts.some(x=>x.status==='Vérifié'))a.push('Contact à vérifier');if(!c.opportunity.logo)a.push('Logo manquant');if(!c.opportunity.decisionMaker||!c.opportunity.deadline)a.push('Besoin à qualifier');if(c.opportunity.stage==='À qualifier')a.push('Statut du devis inconnu');if(c.due&&c.due<=isoDay())a.push('Relance à effectuer');return a}
export function seedClients():Client[]{
const rows=[
['atelier','Atelier Beaumont','Bordeaux','Architecture & design','Textile','AB','blue','Camille Laurent','Responsable communication','Collection équipe · 250 polos',8450,'Devis envoyé',false,'Renouvellement des tenues pour l’ouverture du nouvel atelier. Le devis a été transmis ; le logo vectoriel reste à récupérer.',12,32600,'Récupérer le logo vectoriel',0],
['horizon','Horizon Énergies','Lyon','Énergie','Objets publicitaires','HE','navy','Thomas Mercier','Responsable achats','Welcome packs · 400 unités',12600,'À qualifier',true,'Le client prépare une campagne interne. Le calendrier et la personne qui validera le budget restent à confirmer.',8,28400,'Qualifier le calendrier et le décideur',0],
['maison','Maison Rivage','La Rochelle','Hôtellerie','Bagagerie','MR','sky','Julie Moreau','Directrice marketing','Sacs de plage · 500 unités',6250,'Devis envoyé',true,'Réassort saisonnier de sacs personnalisés. Julie a reçu le devis et souhaite comparer les deux options de marquage.',6,18950,'Relancer le devis et valider le marquage',-1],
['studio','Studio Octave','Nantes','Communication','Textile','SO','lavender','Léa Dubois','Cheffe de projet','Collection événement · 150 pièces',4200,'Devis à préparer',true,'Un nouveau projet événementiel est identifié. L’ancien interlocuteur a quitté l’entreprise ; la remplaçante doit être revérifiée.',4,12100,'Vérifier le rôle de la nouvelle interlocutrice',1],
['terres','Terres & Sens','Angers','Agroalimentaire','Objets publicitaires','TS','pale','Antoine Petit','Responsable communication','Coffrets partenaires · 200 unités',5800,'Devis à préparer',false,'Préparation des cadeaux partenaires de fin d’année. La proposition attend un logo exploitable avant chiffrage du marquage.',9,24800,'Demander le fichier du logo',2],
['collectif','Collectif Azur','Marseille','Association','Textile','CA','ice','Sarah Bernard','Coordinatrice','T-shirts bénévoles · 300 pièces',3900,'Gagné',true,'La commande des bénévoles est confirmée. Préparer le prochain échange pour vérifier la réception et recueillir le retour du client.',5,14650,'Faire le point après livraison',3]
];
return rows.map((r,i)=>({id:r[0] as string,name:r[1] as string,city:r[2] as string,sector:r[3] as string,family:r[4] as string,initials:r[5] as string,color:r[6] as string,summary:r[13] as string,orders:r[14] as number,revenue:r[15] as number,lastOrder:isoDay(-30-i*7),contacts:[{id:`contact-${i}`,name:r[7] as string,role:r[8] as string,email:`contact@${r[0]}.example`,status:i===3?'À revérifier':'Vérifié',verified:i===3?null:isoDay(-7-i)},...(i===3?[{id:'contact-old',name:'Paul Martin',role:'Ancien chef de projet',email:'paul@studio.example',status:'Parti' as const,verified:null}]:[])],opportunity:{name:r[9] as string,amount:r[10] as number,stage:r[11] as Client['opportunity']['stage'],logo:r[12] as boolean,decisionMaker:i===1?'':r[7] as string,deadline:i===1?'':isoDay(15+i*4)},interactions:[{id:`initial-${i}`,date:isoDay(-2-i)+'T10:30:00Z',type:i%2?'Appel':'E-mail',contact:r[7] as string,result:r[13] as string,next:r[16] as string,due:isoDay(r[17] as number)}],next:r[16] as string,due:isoDay(r[17] as number),revision:0}));
}
